version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql
    container_name: db
    platform: linux/amd64
    environment:
      MYSQL_USER: eunmi
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: istory
    ports:
      - "3306:3306"