apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rollout-example
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: v1
    kind: Service
    name: order
  targetCPUUtilizationPercentage: 70
