apiVersion: v1
kind: Service
metadata:
  name: order-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: elb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: order
  ports:
    - name: order
      protocol: TCP
      port: 80
      targetPort: 8080